# Konfigurasi Penerima Kamera UDP & Deteksi ArUco
camera:
  udp_ip: "127.0.0.1"
  udp_port: 5005
  aruco_dict: "DICT_4X4_50"  # Pilihan: DICT_4X4_50, DICT_5X5_50, DICT_6X6_50, dll.
  show_gui: false             # Set ke true untuk menampilkan visualisasi jendela GUI (cv2.imshow) secara langsung
  marker_length: 0.20         # Ukuran fisik ArUco dalam meter (contoh 20cm)

  # Sesuaikan dengan parameter kamera Webots Anda
  camera_matrix: [386.37, 0.0, 160.0, 0.0, 386.37, 120.0, 0.0, 0.0, 1.0]
  dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]
